// Auto-generated normalized seed data from Excel file
export interface Manga {
  id: string;
  titre: string;
  nom_arc_collection: string;
  volume_debut: number;
  volume_fin: number;
  état: string;
  prix_moyen_neuf: number;
  prix_achat_max: number;
  prix_vente_min: number;
  prix_vente_max: number;
  notes?: string;
  hypeScore: number;
  popularity: "Faible" | "Moyenne" | "Forte" | "Très forte";
  tags?: string[];
  isFavorite?: boolean;
}

export const DEFAULT_MANGAS: Manga[] = [
  {
    "id": "one-piece-1-a-10",
    "titre": "One Piece",
    "nom_arc_collection": "One Piece 1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 2.0,
    "prix_vente_min": 2.5,
    "prix_vente_max": 3.5,
    "notes": "",
    "hypeScore": 81,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-10-a-20",
    "titre": "One Piece",
    "nom_arc_collection": "One Piece 10 a 20",
    "volume_debut": 10,
    "volume_fin": 20,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 3.0,
    "prix_vente_min": 3.5,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 82,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-20-et",
    "titre": "One Piece",
    "nom_arc_collection": "One Piece 20 et +",
    "volume_debut": 20,
    "volume_fin": 999,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 3.0,
    "prix_vente_min": 4.0,
    "prix_vente_max": 5.5,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-collector-98-99-100-scell",
    "titre": "One piece",
    "nom_arc_collection": "One piece Collector 98 99 100 scellé",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 30.0,
    "prix_vente_min": 40.0,
    "prix_vente_max": 60.0,
    "notes": "",
    "hypeScore": 84,
    "popularity": "Très forte"
  },
  {
    "id": "fairy-tails-1-a-10",
    "titre": "Fairy Tails",
    "nom_arc_collection": "Fairy Tails 1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.0,
    "prix_vente_min": 1.5,
    "prix_vente_max": 2.0,
    "notes": "",
    "hypeScore": 70,
    "popularity": "Forte"
  },
  {
    "id": "fairy-tails",
    "titre": "Fairy Tails",
    "nom_arc_collection": "Fairy Tails",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 2.0,
    "prix_vente_min": 4.0,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 71,
    "popularity": "Forte"
  },
  {
    "id": "berserk-1-a-9",
    "titre": "Berserk",
    "nom_arc_collection": "Berserk 1 a 9",
    "volume_debut": 1,
    "volume_fin": 9,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 2.0,
    "prix_vente_min": 4.0,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 87,
    "popularity": "Très forte"
  },
  {
    "id": "berserk-10-16",
    "titre": "Berserk",
    "nom_arc_collection": "Berserk 10 16",
    "volume_debut": 10,
    "volume_fin": 16,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 2.25,
    "prix_vente_min": 4.5,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 88,
    "popularity": "Très forte"
  },
  {
    "id": "kingdom",
    "titre": "Kingdom",
    "nom_arc_collection": "Kingdom",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 6.95,
    "prix_achat_max": 2.25,
    "prix_vente_min": 4.5,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 74,
    "popularity": "Forte"
  },
  {
    "id": "spy-x-family",
    "titre": "Spy X Family",
    "nom_arc_collection": "Spy X Family",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "frieren",
    "titre": "Frieren",
    "nom_arc_collection": "Frieren",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 3.0,
    "prix_vente_min": 6.0,
    "prix_vente_max": 6.5,
    "notes": "",
    "hypeScore": 91,
    "popularity": "Très forte"
  },
  {
    "id": "bleach-1-a-10",
    "titre": "Bleach",
    "nom_arc_collection": "Bleach 1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.0,
    "prix_vente_min": 2.0,
    "prix_vente_max": 3.5,
    "notes": "",
    "hypeScore": 77,
    "popularity": "Forte"
  },
  {
    "id": "bleach-11-et",
    "titre": "Bleach",
    "nom_arc_collection": "Bleach 11 et +",
    "volume_debut": 11,
    "volume_fin": 999,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 78,
    "popularity": "Forte"
  },
  {
    "id": "dr-stone",
    "titre": "Dr Stone",
    "nom_arc_collection": "Dr Stone",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "jujutsu-kaisen",
    "titre": "Jujutsu kaisen",
    "nom_arc_collection": "Jujutsu kaisen",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.25,
    "notes": "",
    "hypeScore": 80,
    "popularity": "Très forte"
  },
  {
    "id": "to-your-eternity",
    "titre": "To Your Eternity",
    "nom_arc_collection": "To Your Eternity",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "blue-spring-ride",
    "titre": "Blue Spring Ride",
    "nom_arc_collection": "Blue Spring Ride",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 6.99,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "naruto-1-a-10",
    "titre": "Naruto",
    "nom_arc_collection": "Naruto 1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 0.75,
    "prix_vente_min": 1.5,
    "prix_vente_max": 2.5,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "naruto-11-a-30",
    "titre": "Naruto",
    "nom_arc_collection": "Naruto 11 a 30",
    "volume_debut": 11,
    "volume_fin": 30,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 84,
    "popularity": "Très forte"
  },
  {
    "id": "naruto-40-et",
    "titre": "Naruto",
    "nom_arc_collection": "Naruto 40 et +",
    "volume_debut": 40,
    "volume_fin": 999,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 85,
    "popularity": "Très forte"
  },
  {
    "id": "kengan-ashura",
    "titre": "Kengan Ashura",
    "nom_arc_collection": "Kengan Ashura",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  },
  {
    "id": "solo-leveling-1-a-4",
    "titre": "Solo Leveling",
    "nom_arc_collection": "Solo Leveling 1 a 4",
    "volume_debut": 1,
    "volume_fin": 4,
    "état": "TBE",
    "prix_moyen_neuf": 14.95,
    "prix_achat_max": 4.5,
    "prix_vente_min": 7.0,
    "prix_vente_max": 9.0,
    "notes": "",
    "hypeScore": 52,
    "popularity": "Moyenne"
  },
  {
    "id": "solo-leveling-5-a-20",
    "titre": "Solo Leveling",
    "nom_arc_collection": "Solo Leveling 5 a 20",
    "volume_debut": 5,
    "volume_fin": 20,
    "état": "TBE",
    "prix_moyen_neuf": 14.95,
    "prix_achat_max": 5.0,
    "prix_vente_min": 8.5,
    "prix_vente_max": 11.0,
    "notes": "",
    "hypeScore": 53,
    "popularity": "Moyenne"
  },
  {
    "id": "attaque-des-titans-1-et-10",
    "titre": "Attaque des Titans",
    "nom_arc_collection": "Attaque des Titans 1 et 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.0,
    "prix_vente_min": 2.0,
    "prix_vente_max": 3.0,
    "notes": "",
    "hypeScore": 54,
    "popularity": "Moyenne"
  },
  {
    "id": "attaque-des-titans-10-et",
    "titre": "Attaque des Titans",
    "nom_arc_collection": "Attaque des Titans 10 et +",
    "volume_debut": 10,
    "volume_fin": 999,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "death-note-1-a-13",
    "titre": "Death Note",
    "nom_arc_collection": "Death Note 1 a 13",
    "volume_debut": 1,
    "volume_fin": 13,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 76,
    "popularity": "Forte"
  },
  {
    "id": "vagabond-4-et",
    "titre": "Vagabond",
    "nom_arc_collection": "Vagabond 4 et +",
    "volume_debut": 4,
    "volume_fin": 999,
    "état": "TBE",
    "prix_moyen_neuf": 9.35,
    "prix_achat_max": 3.5,
    "prix_vente_min": 7.0,
    "prix_vente_max": 8.0,
    "notes": "",
    "hypeScore": 57,
    "popularity": "Moyenne"
  },
  {
    "id": "dragon-ball-super-1-a-11",
    "titre": "Dragon ball super",
    "nom_arc_collection": "Dragon ball super 1 a 11",
    "volume_debut": 1,
    "volume_fin": 11,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 58,
    "popularity": "Moyenne"
  },
  {
    "id": "valkyrie-apocalypse-1-a-15",
    "titre": "Valkyrie Apocalypse",
    "nom_arc_collection": "Valkyrie Apocalypse 1 a 15",
    "volume_debut": 1,
    "volume_fin": 15,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "haikyu",
    "titre": "Haikyu",
    "nom_arc_collection": "Haikyu",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 6.95,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 45,
    "popularity": "Faible"
  },
  {
    "id": "detective-conan",
    "titre": "Detective Conan",
    "nom_arc_collection": "Detective Conan",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "jojo-stone-ocean",
    "titre": "Jojo Stone Ocean",
    "nom_arc_collection": "Jojo Stone Ocean",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.29,
    "prix_achat_max": 2.0,
    "prix_vente_min": 4.0,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "demon-slayer",
    "titre": "Demon Slayer",
    "nom_arc_collection": "Demon Slayer",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "viland-saga",
    "titre": "Viland Saga",
    "nom_arc_collection": "Viland Saga",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 2.25,
    "prix_vente_min": 4.5,
    "prix_vente_max": 5.0,
    "notes": "",
    "hypeScore": 49,
    "popularity": "Faible"
  },
  {
    "id": "food-wars-1-a-10",
    "titre": "Food Wars",
    "nom_arc_collection": "Food Wars 1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 6.99,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 50,
    "popularity": "Moyenne"
  },
  {
    "id": "one-punch-man-1-a-15",
    "titre": "One Punch man",
    "nom_arc_collection": "One Punch man 1 a 15",
    "volume_debut": 1,
    "volume_fin": 15,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 3.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  },
  {
    "id": "gintama",
    "titre": "Gintama",
    "nom_arc_collection": "Gintama",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 6.85,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 52,
    "popularity": "Moyenne"
  },
  {
    "id": "d-gray-man",
    "titre": "D Gray Man",
    "nom_arc_collection": "D Gray Man",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 53,
    "popularity": "Moyenne"
  },
  {
    "id": "my-hero-academia",
    "titre": "My Hero Academia",
    "nom_arc_collection": "My Hero Academia",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 74,
    "popularity": "Forte"
  },
  {
    "id": "mashle-1-a-9",
    "titre": "Mashle",
    "nom_arc_collection": "Mashle 1 a 9",
    "volume_debut": 1,
    "volume_fin": 9,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "the-promised-neverland-1-a-10",
    "titre": "The Promised Neverland",
    "nom_arc_collection": "The Promised Neverland  1 a 10",
    "volume_debut": 1,
    "volume_fin": 10,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.25,
    "prix_vente_min": 2.5,
    "prix_vente_max": 3.0,
    "notes": "",
    "hypeScore": 56,
    "popularity": "Moyenne"
  },
  {
    "id": "the-promised-neverland-11-a-19",
    "titre": "The Promised Neverland",
    "nom_arc_collection": "The Promised Neverland  11 a 19",
    "volume_debut": 11,
    "volume_fin": 19,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 57,
    "popularity": "Moyenne"
  },
  {
    "id": "boruto-1-a-11",
    "titre": "Boruto",
    "nom_arc_collection": "Boruto 1 a 11",
    "volume_debut": 1,
    "volume_fin": 11,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 58,
    "popularity": "Moyenne"
  },
  {
    "id": "ao-ashi-1-a-21",
    "titre": "Ao Ashi",
    "nom_arc_collection": "Ao Ashi 1 a 21",
    "volume_debut": 1,
    "volume_fin": 21,
    "état": "TBE",
    "prix_moyen_neuf": 7.95,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "kaiju",
    "titre": "Kaiju",
    "nom_arc_collection": "Kaiju",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 2.0,
    "prix_vente_min": 4.0,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 80,
    "popularity": "Très forte"
  },
  {
    "id": "tokyo-revengers",
    "titre": "Tokyo Revengers",
    "nom_arc_collection": "Tokyo Revengers",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "fire-force",
    "titre": "Fire Force",
    "nom_arc_collection": "Fire Force",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "chainsaw-man",
    "titre": "Chainsaw Man",
    "nom_arc_collection": "Chainsaw Man",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.0,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "full-metal-alchimliste",
    "titre": "Full Metal Alchimliste",
    "nom_arc_collection": "Full Metal Alchimliste",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.2,
    "prix_achat_max": 1.25,
    "prix_vente_min": 2.5,
    "prix_vente_max": 3.0,
    "notes": "",
    "hypeScore": 49,
    "popularity": "Faible"
  },
  {
    "id": "seraph-of-the-end",
    "titre": "Seraph of The End",
    "nom_arc_collection": "Seraph of The End",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.75,
    "prix_vente_min": 3.5,
    "prix_vente_max": 4.5,
    "notes": "",
    "hypeScore": 50,
    "popularity": "Moyenne"
  },
  {
    "id": "black-clover",
    "titre": "Black Clover",
    "nom_arc_collection": "Black Clover",
    "volume_debut": 1,
    "volume_fin": 1,
    "état": "TBE",
    "prix_moyen_neuf": 7.3,
    "prix_achat_max": 1.5,
    "prix_vente_min": 3.0,
    "prix_vente_max": 3.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  }
];
