// Auto-generated seed data from Excel file
export interface Manga {
  id: string;
  title: string;
  series: string;
  volumeRange: string;
  condition: string;
  retailPrice: number;
  maxBuyPrice: number;
  minSellPrice: number;
  maxSellPrice: number;
  notes: string;
  hypeScore: number;
  popularity: "Faible" | "Moyenne" | "Forte" | "Très forte";
  tags?: string[];
  isFavorite?: boolean;
}

export const DEFAULT_MANGAS: Manga[] = [
  {
    "id": "one-piece-1-a-10",
    "title": "One Piece 1 a 10",
    "series": "One Piece",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 2.0,
    "minSellPrice": 2.5,
    "maxSellPrice": 3.5,
    "notes": "",
    "hypeScore": 81,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-10-a-20",
    "title": "One Piece 10 a 20",
    "series": "One Piece",
    "volumeRange": "10 à 20",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 3.0,
    "minSellPrice": 3.5,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 82,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-20-et",
    "title": "One Piece 20 et +",
    "series": "One Piece",
    "volumeRange": "20 & +",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 3.0,
    "minSellPrice": 4.0,
    "maxSellPrice": 5.5,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "one-piece-collector-98-99-100-scell",
    "title": "One piece Collector 98 99 100 scellé",
    "series": "One piece",
    "volumeRange": "Collector",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 30.0,
    "minSellPrice": 40.0,
    "maxSellPrice": 60.0,
    "notes": "",
    "hypeScore": 84,
    "popularity": "Très forte"
  },
  {
    "id": "fairy-tails-1-a-10",
    "title": "Fairy Tails 1 a 10",
    "series": "Fairy Tails",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.0,
    "minSellPrice": 1.5,
    "maxSellPrice": 2.0,
    "notes": "",
    "hypeScore": 70,
    "popularity": "Forte"
  },
  {
    "id": "fairy-tails",
    "title": "Fairy Tails",
    "series": "Fairy Tails",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 2.0,
    "minSellPrice": 4.0,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 71,
    "popularity": "Forte"
  },
  {
    "id": "berserk-1-a-9",
    "title": "Berserk 1 a 9",
    "series": "Berserk",
    "volumeRange": "1 à 9",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 2.0,
    "minSellPrice": 4.0,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 87,
    "popularity": "Très forte"
  },
  {
    "id": "berserk-10-16",
    "title": "Berserk 10 16",
    "series": "Berserk 10 16",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 2.25,
    "minSellPrice": 4.5,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 88,
    "popularity": "Très forte"
  },
  {
    "id": "kingdom",
    "title": "Kingdom",
    "series": "Kingdom",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 6.95,
    "maxBuyPrice": 2.25,
    "minSellPrice": 4.5,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 74,
    "popularity": "Forte"
  },
  {
    "id": "spy-x-family",
    "title": "Spy X Family",
    "series": "Spy X Family",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "frieren",
    "title": "Frieren",
    "series": "Frieren",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 3.0,
    "minSellPrice": 6.0,
    "maxSellPrice": 6.5,
    "notes": "",
    "hypeScore": 91,
    "popularity": "Très forte"
  },
  {
    "id": "bleach-1-a-10",
    "title": "Bleach 1 a 10",
    "series": "Bleach",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.0,
    "minSellPrice": 2.0,
    "maxSellPrice": 3.5,
    "notes": "",
    "hypeScore": 77,
    "popularity": "Forte"
  },
  {
    "id": "bleach-11-et",
    "title": "Bleach 11 et +",
    "series": "Bleach",
    "volumeRange": "11 & +",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 78,
    "popularity": "Forte"
  },
  {
    "id": "dr-stone",
    "title": "Dr Stone",
    "series": "Dr Stone",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "jujutsu-kaisen",
    "title": "Jujutsu kaisen",
    "series": "Jujutsu kaisen",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.25,
    "notes": "",
    "hypeScore": 80,
    "popularity": "Très forte"
  },
  {
    "id": "to-your-eternity",
    "title": "To Your Eternity",
    "series": "To Your Eternity",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "blue-spring-ride",
    "title": "Blue Spring Ride",
    "series": "Blue Spring Ride",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 6.99,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "naruto-1-a-10",
    "title": "Naruto 1 a 10",
    "series": "Naruto",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 0.75,
    "minSellPrice": 1.5,
    "maxSellPrice": 2.5,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "naruto-11-a-30",
    "title": "Naruto 11 a 30",
    "series": "Naruto",
    "volumeRange": "11 à 30",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 84,
    "popularity": "Très forte"
  },
  {
    "id": "naruto-40-et",
    "title": "Naruto 40 et +",
    "series": "Naruto",
    "volumeRange": "40 & +",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 85,
    "popularity": "Très forte"
  },
  {
    "id": "kengan-ashura",
    "title": "Kengan Ashura",
    "series": "Kengan Ashura",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  },
  {
    "id": "solo-leveling-1-a-4",
    "title": "Solo Leveling 1 a 4",
    "series": "Solo Leveling",
    "volumeRange": "1 à 4",
    "condition": "TBE",
    "retailPrice": 14.95,
    "maxBuyPrice": 4.5,
    "minSellPrice": 7.0,
    "maxSellPrice": 9.0,
    "notes": "",
    "hypeScore": 52,
    "popularity": "Moyenne"
  },
  {
    "id": "solo-leveling-5-a-20",
    "title": "Solo Leveling 5 a 20",
    "series": "Solo Leveling",
    "volumeRange": "5 à 20",
    "condition": "TBE",
    "retailPrice": 14.95,
    "maxBuyPrice": 5.0,
    "minSellPrice": 8.5,
    "maxSellPrice": 11.0,
    "notes": "",
    "hypeScore": 53,
    "popularity": "Moyenne"
  },
  {
    "id": "attaque-des-titans-1-et-10",
    "title": "Attaque des Titans 1 et 10",
    "series": "Attaque des Titans",
    "volumeRange": "1 et 10",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.0,
    "minSellPrice": 2.0,
    "maxSellPrice": 3.0,
    "notes": "",
    "hypeScore": 54,
    "popularity": "Moyenne"
  },
  {
    "id": "attaque-des-titans-10-et",
    "title": "Attaque des Titans 10 et +",
    "series": "Attaque des Titans",
    "volumeRange": "10 & +",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "death-note-1-a-13",
    "title": "Death Note 1 a 13",
    "series": "Death Note",
    "volumeRange": "1 à 13",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 76,
    "popularity": "Forte"
  },
  {
    "id": "vagabond-4-et",
    "title": "Vagabond 4 et +",
    "series": "Vagabond",
    "volumeRange": "4 & +",
    "condition": "TBE",
    "retailPrice": 9.35,
    "maxBuyPrice": 3.5,
    "minSellPrice": 7.0,
    "maxSellPrice": 8.0,
    "notes": "",
    "hypeScore": 57,
    "popularity": "Moyenne"
  },
  {
    "id": "dragon-ball-super-1-a-11",
    "title": "Dragon ball super 1 a 11",
    "series": "Dragon ball super",
    "volumeRange": "1 à 11",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 58,
    "popularity": "Moyenne"
  },
  {
    "id": "valkyrie-apocalypse-1-a-15",
    "title": "Valkyrie Apocalypse 1 a 15",
    "series": "Valkyrie Apocalypse",
    "volumeRange": "1 à 15",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "haikyu",
    "title": "Haikyu",
    "series": "Haikyu",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 6.95,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 45,
    "popularity": "Faible"
  },
  {
    "id": "detective-conan",
    "title": "Detective Conan",
    "series": "Detective Conan",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "jojo-stone-ocean",
    "title": "Jojo Stone Ocean",
    "series": "Jojo Stone Ocean",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.29,
    "maxBuyPrice": 2.0,
    "minSellPrice": 4.0,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "demon-slayer",
    "title": "Demon Slayer",
    "series": "Demon Slayer",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "viland-saga",
    "title": "Viland Saga",
    "series": "Viland Saga",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 2.25,
    "minSellPrice": 4.5,
    "maxSellPrice": 5.0,
    "notes": "",
    "hypeScore": 49,
    "popularity": "Faible"
  },
  {
    "id": "food-wars-1-a-10",
    "title": "Food Wars 1 a 10",
    "series": "Food Wars",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 6.99,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 50,
    "popularity": "Moyenne"
  },
  {
    "id": "one-punch-man-1-a-15",
    "title": "One Punch man 1 a 15",
    "series": "One Punch man",
    "volumeRange": "1 à 15",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 3.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  },
  {
    "id": "gintama",
    "title": "Gintama",
    "series": "Gintama",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 6.85,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 52,
    "popularity": "Moyenne"
  },
  {
    "id": "d-gray-man",
    "title": "D Gray Man",
    "series": "D Gray Man",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 53,
    "popularity": "Moyenne"
  },
  {
    "id": "my-hero-academia",
    "title": "My Hero Academia",
    "series": "My Hero Academia",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 74,
    "popularity": "Forte"
  },
  {
    "id": "mashle-1-a-9",
    "title": "Mashle 1 a 9",
    "series": "Mashle",
    "volumeRange": "1 à 9",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 55,
    "popularity": "Moyenne"
  },
  {
    "id": "the-promised-neverland-1-a-10",
    "title": "The Promised Neverland  1 a 10",
    "series": "The Promised Neverland",
    "volumeRange": "1 à 10",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.25,
    "minSellPrice": 2.5,
    "maxSellPrice": 3.0,
    "notes": "",
    "hypeScore": 56,
    "popularity": "Moyenne"
  },
  {
    "id": "the-promised-neverland-11-a-19",
    "title": "The Promised Neverland  11 a 19",
    "series": "The Promised Neverland",
    "volumeRange": "11 à 19",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 57,
    "popularity": "Moyenne"
  },
  {
    "id": "boruto-1-a-11",
    "title": "Boruto 1 a 11",
    "series": "Boruto",
    "volumeRange": "1 à 11",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 58,
    "popularity": "Moyenne"
  },
  {
    "id": "ao-ashi-1-a-21",
    "title": "Ao Ashi 1 a 21",
    "series": "Ao Ashi",
    "volumeRange": "1 à 21",
    "condition": "TBE",
    "retailPrice": 7.95,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 59,
    "popularity": "Moyenne"
  },
  {
    "id": "kaiju",
    "title": "Kaiju",
    "series": "Kaiju",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 2.0,
    "minSellPrice": 4.0,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 80,
    "popularity": "Très forte"
  },
  {
    "id": "tokyo-revengers",
    "title": "Tokyo Revengers",
    "series": "Tokyo Revengers",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 46,
    "popularity": "Faible"
  },
  {
    "id": "fire-force",
    "title": "Fire Force",
    "series": "Fire Force",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 47,
    "popularity": "Faible"
  },
  {
    "id": "chainsaw-man",
    "title": "Chainsaw Man",
    "series": "Chainsaw Man",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.0,
    "notes": "",
    "hypeScore": 83,
    "popularity": "Très forte"
  },
  {
    "id": "full-metal-alchimliste",
    "title": "Full Metal Alchimliste",
    "series": "Full Metal Alchimliste",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.2,
    "maxBuyPrice": 1.25,
    "minSellPrice": 2.5,
    "maxSellPrice": 3.0,
    "notes": "",
    "hypeScore": 49,
    "popularity": "Faible"
  },
  {
    "id": "seraph-of-the-end",
    "title": "Seraph of The End",
    "series": "Seraph of The End",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.75,
    "minSellPrice": 3.5,
    "maxSellPrice": 4.5,
    "notes": "",
    "hypeScore": 50,
    "popularity": "Moyenne"
  },
  {
    "id": "black-clover",
    "title": "Black Clover",
    "series": "Black Clover",
    "volumeRange": "Tome Unique / Lot",
    "condition": "TBE",
    "retailPrice": 7.3,
    "maxBuyPrice": 1.5,
    "minSellPrice": 3.0,
    "maxSellPrice": 3.5,
    "notes": "",
    "hypeScore": 51,
    "popularity": "Moyenne"
  }
];
